name: Build

on:
  pull_request:
  push:
    tags:
      - 'build*' # Push events to matching build* tags

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Download exiftool
      run: |
        New-Item -Path "./exiftool" -ItemType "directory" -Force | Out-Null
        Invoke-WebRequest -Uri "https://github.com/leslievan/semi-utils/raw/exiftool/exiftool/exiftool.exe" -OutFile "./exiftool/exiftool.exe"

    - name: Build Executable
      run: |
        pyinstaller main.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: semi-utils-latest
        path: dist
